name = "Asgard"
author = "Millennium"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2dbd2c31db78c901e7d61983cc935af3a5ecce619532eea6ef36afd41250c59d"

[versions]
forge = "40.3.12"
minecraft = "1.18.2"
