name = "Asgard"
author = "Millennium"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4e79b4cf46004ff8924dad0148f27ec74ff3b155ed456188ab2a425b70e1713f"

[versions]
forge = "40.3.12"
minecraft = "1.18.2"
