name = "Asgard"
author = "Millennium"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4285fad07829f2d0c657f33053f20d08660feb1c5c2c4f8d7c7468e19a7951cb"

[versions]
forge = "40.3.12"
minecraft = "1.18.2"
