onEvent('block.registry', event => {

    //Vault Trash
    event.create('the_vault:silver_scrap_1').displayName('1x Compressed Silver Scrap').tagBlock('minecraft:mineable/pickaxe')
    event.create('the_vault:silver_scrap_2').displayName('2x Compressed Silver Scrap').tagBlock('minecraft:mineable/pickaxe')
    event.create('the_vault:vault_stone_1').displayName('1x Compressed Vault Stone').tagBlock('minecraft:mineable/pickaxe')
    event.create('the_vault:vault_stone_2').displayName('2x Compressed Vault Stone').tagBlock('minecraft:mineable/pickaxe')
    event.create('the_vault:vault_cobblestone_1').displayName('1x Compressed Vault Cobblestone').tagBlock('minecraft:mineable/pickaxe')
    event.create('the_vault:vault_cobblestone_2').displayName('2x Compressed Vault Cobblestone').tagBlock('minecraft:mineable/pickaxe')
    event.create('the_vault:vault_plating_block').displayName('1x Compressed Vault Plating').tagBlock('minecraft:mineable/pickaxe')
    event.create('the_vault:vault_plating_block_1').displayName('2x Compressed Vault Plating').tagBlock('minecraft:mineable/pickaxe')
    event.create('the_vault:ancient_copper_block_1').displayName('1x Compressed Ancient Copper Block').tagBlock('minecraft:mineable/pickaxe')
    event.create('the_vault:living_rock_block_cobble_1').displayName('1x Compressed Living Rock Block').tagBlock('minecraft:mineable/pickaxe')
    event.create('the_vault:magic_silk_block_1').displayName('1x Compressed Magic Silk Block').tagBlock('minecraft:mineable/pickaxe')
    event.create('the_vault:ornate_block_1').displayName('1x Compressed Ornate Block').tagBlock('minecraft:mineable/pickaxe')
    event.create('the_vault:rotten_meat_block_1').displayName('1x Compressed Rotten Meat Block').tagBlock('minecraft:mineable/pickaxe')
    event.create('the_vault:sandy_block_1').displayName('1x Compressed Sandy Block').tagBlock('minecraft:mineable/pickaxe')
    event.create('the_vault:velvet_block_1').displayName('1x Compressed Velvet Block').tagBlock('minecraft:mineable/pickaxe')
    event.create('the_vault:gilded_block_1').displayName('1x Compressed Gilded Block').tagBlock('minecraft:mineable/pickaxe')
    event.create('the_vault:mossy_bone_block_1').displayName('1x Compressed Mossy Bone Block').tagBlock('minecraft:mineable/pickaxe')

    //Gem Blocks
    //event.create('the_vault:block_gem_larimar').displayName('Block of Larimar Gem').tagBlock('forge:storage_blocks/larimar').tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:beacon_base_blocks')
    //event.create('the_vault:block_gem_benitoite').displayName('Block of Benitoite Gem').tagBlock('forge:storage_blocks/benitoite').tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:beacon_base_blocks')
    //event.create('the_vault:block_gem_wutodie').displayName('Block of Wutodie Gem').tagBlock('forge:storage_blocks/wutodie').tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:beacon_base_blocks')
    //event.create('the_vault:block_gem_painite').displayName('Block of Painite Gem').tagBlock('forge:storage_blocks/painite').tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:beacon_base_blocks')
    //event.create('the_vault:block_gem_alexandrite').displayName('Block of Alexandrite Gem').tagBlock('forge:storage_blocks/alexandrite').tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:beacon_base_blocks')
    //event.create('the_vault:block_gem_black_opal').displayName('Block of Black Opal Gem').tagBlock('forge:storage_blocks/black_opal').tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:beacon_base_blocks')
    //event.create('the_vault:block_gem_echo').displayName('Block of Echo Gem').tagBlock('forge:storage_blocks/echo').tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:beacon_base_blocks')
    //event.create('the_vault:block_gem_sparkletine').displayName('Block of Sparkletine Gem').tagBlock('forge:storage_blocks/sparkletine').tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:beacon_base_blocks')
    //event.create('the_vault:block_gem_iskallium').displayName('Block of Woldium Gem').tagBlock('forge:storage_blocks/iskallium').tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:beacon_base_blocks')
    //event.create('the_vault:block_gem_upaline').displayName('Block of Upaline Gem').tagBlock('forge:storage_blocks/upaline').tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:beacon_base_blocks')
    //event.create('the_vault:block_gem_xenium').displayName('Block of Xeenium Gem').tagBlock('forge:storage_blocks/xenium').tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:beacon_base_blocks')
    //event.create('the_vault:block_gem_petzanite').displayName('Block of Petezanite Gem').tagBlock('forge:storage_blocks/petzanite').tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:beacon_base_blocks')
    //event.create('the_vault:block_gem_gorginite').displayName('Block of Gorginite Gem').tagBlock('forge:storage_blocks/gorginite').tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:beacon_base_blocks')
    //event.create('the_vault:block_gem_bomignite').displayName('Block of Bomignite Gem').tagBlock('forge:storage_blocks/bomignite').tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:beacon_base_blocks')
    //event.create('the_vault:block_gem_tubium').displayName('Block of Tubium Gem').tagBlock('forge:storage_blocks/tubium').tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:beacon_base_blocks')
    //event.create('the_vault:block_gem_ashium').displayName('Block of Ashium Gem').tagBlock('forge:storage_blocks/ashium').tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:beacon_base_blocks')

    // Unobtanium
	event.create('white_unobtanium_block').displayName('White Unobtanium Block').material('metal').hardness(50.0).tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:needs_iron_tool').requiresTool(true)
	event.create('orange_unobtanium_block').displayName('Orange Unobtanium Block').material('metal').hardness(50.0).tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:needs_iron_tool').requiresTool(true)
	event.create('magenta_unobtanium_block').displayName('Magenta Unobtanium Block').material('metal').hardness(50.0).tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:needs_iron_tool').requiresTool(true)
	event.create('light_blue_unobtanium_block').displayName('Light Blue Unobtanium Block').material('metal').hardness(50.0).tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:needs_iron_tool').requiresTool(true)
	event.create('yellow_unobtanium_block').displayName('Yellow Unobtanium Block').material('metal').hardness(50.0).tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:needs_iron_tool').requiresTool(true)
	event.create('lime_unobtanium_block').displayName('Lime Unobtanium Block').material('metal').hardness(50.0).tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:needs_iron_tool').requiresTool(true)
	event.create('pink_unobtanium_block').displayName('Pink Unobtanium Block').material('metal').hardness(50.0).tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:needs_iron_tool').requiresTool(true)
	event.create('gray_unobtanium_block').displayName('Gray Unobtanium Block').material('metal').hardness(50.0).tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:needs_iron_tool').requiresTool(true)
	event.create('light_gray_unobtanium_block').displayName('Light Gray Unobtanium Block').material('metal').hardness(50.0).tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:needs_iron_tool').requiresTool(true)
	event.create('cyan_unobtanium_block').displayName('Cyan Unobtanium Block').material('metal').hardness(50.0).tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:needs_iron_tool').requiresTool(true)
	event.create('blue_unobtanium_block').displayName('Blue Unobtanium Block').material('metal').hardness(50.0).tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:needs_iron_tool').requiresTool(true)
	event.create('brown_unobtanium_block').displayName('Brown Unobtanium Block').material('metal').hardness(50.0).tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:needs_iron_tool').requiresTool(true)
	event.create('green_unobtanium_block').displayName('Green Unobtanium Block').material('metal').hardness(50.0).tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:needs_iron_tool').requiresTool(true)
	event.create('red_unobtanium_block').displayName('Red Unobtanium Block').material('metal').hardness(50.0).tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:needs_iron_tool').requiresTool(true)
	event.create('purple_unobtanium_block').displayName('Purple Unobtanium Block').material('metal').hardness(50.0).tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:needs_iron_tool').requiresTool(true)
	event.create('black_unobtanium_block').displayName('Black Unobtanium Block').material('metal').hardness(50.0).tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:needs_iron_tool').requiresTool(true)
	event.create('rainbow_unobtanium_block').displayName('Rainbow Unobtanium Block').material('metal').hardness(50.0).tagBlock('minecraft:mineable/pickaxe').tagBlock('minecraft:needs_iron_tool').requiresTool(true)

})

onEvent('item.registry', event => {
	// Unobtanium
	event.create('white_unobtanium').displayName('White Unobtanium')
	event.create('orange_unobtanium').displayName('Orange Unobtanium')
	event.create('magenta_unobtanium').displayName('Magenta Unobtanium')
	event.create('light_blue_unobtanium').displayName('Light Blue Unobtanium')
	event.create('yellow_unobtanium').displayName('Yellow Unobtanium')
	event.create('lime_unobtanium').displayName('Lime Unobtanium')
	event.create('pink_unobtanium').displayName('Pink Unobtanium')
	event.create('gray_unobtanium').displayName('Gray Unobtanium')
	event.create('light_gray_unobtanium').displayName('Light Gray Unobtanium')
	event.create('cyan_unobtanium').displayName('Cyan Unobtanium')
	event.create('blue_unobtanium').displayName('Blue Unobtanium')
	event.create('brown_unobtanium').displayName('Brown Unobtanium')
	event.create('green_unobtanium').displayName('Green Unobtanium')
	event.create('red_unobtanium').displayName('Red Unobtanium')
	event.create('purple_unobtanium').displayName('Purple Unobtanium')
	event.create('black_unobtanium').displayName('Black Unobtanium')
	event.create('rainbow_unobtanium').displayName('Rainbow Unobtanium')
})
