
["BetterVHBlockModels Common Config"]
	#Enable the Ascension Forge Block Hitbox
	ASCENSION_FORGE = false
	#Enable the Black Market Block Hitbox
	BLACK_MARKET = true
	#Enable the Bounty Block Hitbox
	BOUNTY_BLOCK = true
	#Enable the Card Essence Extractor Block Hitbox
	CARD_ESSENCE_EXTRACTOR = true
	#Enable the Crake Pedestal Block Hitbox
	CRAKE_PEDESTAL_BLOCK = true
	#Enable the Crystal Workbench Block Hitbox
	CRYSTAL_WORKBENCH = true
	#Enable the Easter Egg Block Hitbox
	EASTER_EGG = true
	#Enable the Grid Gateway Block Hitbox
	GRID_GATEWAY = true
	#Enable the Herald Controller Block Hitbox
	HERALD_CONTROLLER = true
	#Enable the Inscription Table Block Hitbox
	INSCRIPTION_TABLE = true
	#Enable the Lodestone Block Hitbox
	LODESTONE = true
	#Enable the Monolith Block Hitbox
	MONOLITH = true
	#Enable the MVP Crown Block Hitbox
	MVP_CROWN = true
	#Enable the Obelisk Block Hitbox
	OBELISK = true
	#Enable the Pylon Block Hitbox
	PYLON = true
	#Enable the Relic Pedestal Block Hitbox
	RELIC_PEDESTAL = true
	#Enable the Scavenger Altar Block Hitbox
	SCAVENGER_ALTAR = true
	#Enable the Shop Pedestal Block Hitbox
	SHOP_PEDESTAL = true
	#Enable the Skill Altar Block Hitbox
	SKILL_ALTAR = true
	#Enable the Spirit Extractor Block Hitbox
	SPIRIT_EXTRACTOR = true
	#Enable the Stabilizer Block Hitbox
	STABILIZER = true
	#Enable the Toolstation Block Hitbox
	TOOLSTATION = true
	#Enable the Vault Crate Block Hitbox
	VAULT_CRATE = true
	#Enable the Vault Enchanter Block Hitbox
	VAULT_ENCHANTER = true
	#Enable the Jewel Applicator Block Hitbox
	JEWEL_APPLICATOR = true
	#Enable the Wardrobe Block Hitbox
	WARDROBE = true
	#Enable the Offering Pillar Block Hitbox
	OFFERING_PILLAR = true
	#Enable the Vault Altar Block Hitbox
	VAULT_ALTAR = false
	#Enable the Enhancement Altar Block Hitbox
	ENHANCEMENT_ALTAR = true
	#Enable the Demagnetizer Block Hitbox
	DEMAGNETIZER = true
	#Enable the Vault Diffuser Block Hitbox
	VAULT_DIFFUSER = true
	#Enable the Soul Harvester Block Hitbox
	SOUL_HARVESTER = true
	#Enable the Vault Recycler Block Hitbox
	VAULT_RECYCLER = true
	#Enable the Modifier Archive Block Hitbox
	MODIFIER_ARCHIVE = true
	#Enable the Animatrix Block Hitbox
	ANIMATRIX = true
	#Enable the Debagnetizer Block Hitbox
	DEBAGNETIZER = true
	#Enable the Vault Forge Block Hitbox
	VAULT_FORGE = true
	#Enable the Artisan Station Block Hitbox
	ARTISAN_STATION = true
	#Enable the Modifier Workbench Block Hitbox
	MODIFIER_WORKBENCH = true

