
# Legendary Tooltips Configuration Instructions
#
# *** READ THIS FIRST ***
#
# By default, this mod does not apply special borders to most items.  It was designed to work well with mod packs where
# the available selection of items can vary widely, so it is up to the user or mod pack designer to customize as needed.
# There are many options available for setting up which custom borders (also called frames) apply to which items.  Follow these steps:
#   1. Decide which items you want to have custom borders, and which borders.  Note that each custom border has a number associated with it (starting at 0).
#   2. For each custom border you want to use, fill out the associated list in the "definitions" section.  This will be filled out with a list of "selectors",
#      each of which tell the mod what items have that border.  Please read the information above the definitions section for specifics.
#   3. Selectors for borders are checked in the order provided in the "priorities" section.  Once a match is found, that border is displayed.
#      For example, if border 0 had the selector "%Diamond" and border 1 had the selector "diamond_sword", they would both match for diamond swords.
#      In this case, whichever border number came first in the priority list would be the border that would get drawn in-game.
#   4. Optionally, border colors associated with custom borders can be set in the "colors" section.  The start color is the color at the top of the tooltip,
#      and the end color is the bottom, with a smooth transition between.  Please read the information above the color section for specifics.
[client]

	[client.visual_options]
		# Whether item names in tooltips should have a line under them separating them from the rest of the tooltip.
		name_separator = true
		# If enabled, tooltip border colors will match item rarity colors (except for custom borders).
		borders_match_rarity = true
		# If enabled, tooltips will display a drop shadow.
		tooltip_shadow = true
		# If enabled, items showing a custom border will have a special shine effect when hovered over.
		shine_effect = true
		# If enabled, tooltip titles will be drawn centered.
		centered_title = true
		# If enabled, tooltips with custom borders will always be at least wide enough to display all border decorations.
		enforce_minimum_width = false

	# Entry types:
	#    Item name - Use item name for vanilla items or include mod name for modded items.  Examples: "minecraft:stick", "iron_ore"
	#    Tag - $ followed by tag name.  Examples: "$forge:stone", "$planks"
	#    Mod name - @ followed by mod identifier.  Examples: "@spoiledeggs"
	#    Rarity - ! followed by item's rarity.  This is ONLY vanilla rarities.  Examples: "!uncommon", "!rare", "!epic"
	#    Item name color - # followed by color hex code, the hex code must match exactly.  Examples: "#23F632"
	#    Display name - % followed by any text.  Will match any item with this text in its tooltip display name.  Examples: "%Netherite", "%[Uncommon]"
	#    Tooltip text - Will match any item with this text anywhere in the tooltip text (besides the name).  Examples: "^Legendary"
	#    NBT tag - & followed by tag name and optional comparator (=, >, <, or !=) and value, in the format <tag><comparator><value> or just <tag>.  Examples: "&Damage=0", "&Tier>1", "&map!=128", "&Enchantments"
	[client.definitions]
		level0_entries = ["!epic", "!rare"]
		level1_entries = ["%Power Crystal"]
		level2_entries = ["%Vault Helmet", "%Vault Chestplate", "%Vault Leggings", "%Vault Boots", "%Vault Sword", "%Vault Axe", "the_vault:wand", "the_vault:focus", "%Vault Shield", "%Vault Magnet", "%Vault Trident", "%Vault Battlestaff", "%Vault Plushie", "%Vault Sack"]
		level3_entries = ["%Vaulterite"]
		level4_entries = ["%Black Chromatic Steel", "%Vault Anvil"]
		level5_entries = ["%Bomignite", "%bomignite"]
		level6_entries = ["%Woldium", "%woldium"]
		level7_entries = ["%Petezanite", "%petezanite"]
		level8_entries = ["%Ashium", "%ashium"]
		level9_entries = ["%Upaline", "%upaline"]
		level10_entries = ["%Echo", "%Echoing"]
		level11_entries = ["%POG", "%Pog", "%Prismatic", "%Wold Star", "%Keychain", "%Omega Box", "%Catalyst Box", "%Gem_Box", "%Smashed Vault"]
		level12_entries = ["%Gorginite", "%gorginite"]
		level13_entries = ["%Sparkletine", "%sparkletine"]
		level14_entries = ["%Tubium", "%tubium"]
		level15_entries = ["%xeenium", "%Xeenium"]
		# Enter blacklist selectors here using the same format as above. Any items that match these selectors will NOT show a border.
		blacklist = []

	# Set border priorities here.  This should be a list of numbers that correspond to border levels, with numbers coming first being higher priority.
	# Optionally, -1 can be inserted to indicate relative priority of data and api-defined borders.  If you don't know what that means, you don't need to worry about it.
	[client.priorities]
		priorities = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

	# The colors used for each tooltip, in this order: top border color, bottom border color, top background color, bottom background color.
	# None of these colors are required, though any colors not specified will be replaced with the default tooltip colors.
	#
	# VALID COLOR FORMATS
	#   Hex color code - A hex color code is preceded by # or 0x and must be quoted.  Supports 3, 4, 6, or 8 digit codes in the formats RGB, ARGB, RRGGBB, AARRGGBB.
	#     Examples: "#F4C", "0xFEE0", "#40FF2E", "#CC00E2EE"
	#
	#   Decimal color code - A decimal color code, which is just a hex color code converted to decimal.  May or may not be quoted.
	#     Examples: 15614720, "4278251143"
	#
	#   Minecraft color name - One of the standard 16 Minecraft color names.  Must be quoted.
	#     Examples: "red", "dark_purple", "gold"
	#
	#   Web color name - One of the standard 140 web/HTML color names or "transparent".  Must be quoted.
	#     Examples: "chartreuse", "darkorange", "deeppink", "deepskyblue"
	#
	#   Modifiers - Colors specified in any of the above formats can be modified by using modifiers.
	#         Modifiers are specified after any color in the format "<+, -, or =><h, s, v, r, g, b, or a><amount>".
	#         The letters represent h - hue, s - saturation, v - value, r - red, g - green, b - blue, a - alpha.
	#         Valid amounts are 0 to 255 for all types except hue, which accepts 0 to 359.
	#     Examples: "red+h15", "#saddlebrown-v20+s5", "10_aqua_aqua+v15-h5", "#F4C-r15-v10=a40"
	#
	#   Animated color - An animated color that fades from one to another in sequence.
	#         A string in the format "<duration in seconds>_<list of color definitions separated by underscores>".  Must be quoted.
	#     Examples: "10_black_#7FFF00", "5.5_gold_orange_orangered", "20_red_orange_yellow_green_blue_purple"
	[client.colors]
		level0_colors = [-6723294, -10864099, -266991104, -401208832]
		level1_colors = ["30_#f063cb_#eb35bb_#AA1181_#7C0C5E", "30_#7C0C5E_#AA1181_#eb35bb_#f063cb", "auto", "auto"]
		level2_colors = ["30_#777777_#363636", "30_#363636_#777777", "auto", "auto"]
		level3_colors = ["35_#960209_#721216_#6c4d4e", "35_#6c4d4e_#721216_#960209", "auto", "auto"]
		level4_colors = ["35_#50495d_#524b59_#544c56_#414e5f_#464f5c_#45485f_#4a4a5d_#3f585f", "35_#3f585f_#4a4a5d_#45485f_#464f5c_#414e5f_#544c56_#524b59_#50495d", "auto", "auto"]
		level5_colors = ["30_#E03847_#3F7BDA", "30_#E03847_#3F7BDA", "auto", "auto"]
		level6_colors = ["#a83ff6", "#a83ff6", "auto", "auto"]
		level7_colors = ["#7BE1B0", "#7BE1B0", "auto", "auto"]
		level8_colors = ["#D9772F", "#D9772F", "auto", "auto"]
		level9_colors = ["#F8DFF4", "#F8DFF4", "auto", "auto"]
		level10_colors = ["30_#1a0133_#4e0599", "30_#4e0599_#1a0133", "auto", "auto"]
		level11_colors = ["30_#6FE400_#0249F4_#FF21F_#DF1A1A", "30_#6FE400_#0249F4_#FF21F_#DF1A1A", "auto", "auto"]
		level12_colors = ["#CE1E77", "#CE1E77", "auto", "auto"]
		level13_colors = ["#C1A705", "#C1A705", "auto", "auto"]
		level14_colors = ["#027441", "#027441", "auto", "auto"]
		level15_colors = ["#322589", "#322589", "auto", "auto"]

